config/routes.rb
Rails.application.routes.draw do
  # Devise Routes
  devise_for :user, path: 'auth', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'register',
      sign_up: 'signup'
  }, controllers: {
      # :registrations => 'registrations',
      # :sessions => 'sessions',
      :omniauth_callbacks => 'omniauth_callbacks'
  }

  authenticate :user, lambda { |u| u.admin? } do
    get '/analytics' => 'analytics#index', as: :analytics
    get '/analytics/show' => 'analytics#show'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount_rails_db_info as: 'rails_db_info_engine' if Rails.env.development?
  root 'home#index'

  # Rate
  post '/rate' => 'rater#create', as: :rate

  # Add routes
  get '/quem-somos' => 'about#index', as: :about
  get '/anuncie' => 'ads#index', as: :ads
  get '/ofertas/(:category)' => 'products#list_by_category', as: :list_products_by_category
  get '/ofertas/(:category)/(:subcategory)' => 'products#list_by_subcategory', as: :list_products_by_subcategory
  get '/ofertas/(:category)/(:subcategory)/(:slug)' => 'products#list_by_name', as: :list_products_by_name
  get '/:type_company/:slug' => 'company#index', as: :company

  # search
  get '/search' => 'search#index', as: :search

  # Error routes
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"
end

app/views/layouts/_alerts.html.erb
<% flash.each do |key, value| %>
	<%
		if key != 'success' && key != 'danger' && key != 'notice'
			key = 'danger'
		end
	%>
    <div class="alert-message alert-message-<%= key %>">
      <button type="button" class="close">&times;</button>
      <%= value.html_safe %>
    </div>
<% end %>

app/views/layouts/_head_devise.erb
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<title>Andemenos.com</title>

	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<%= favicon_link_tag 'icon.png' %>

	<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

	<%= stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'modernizr' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>

app/views/layouts/_info_devise.html.erb
<p class="text-information">Para poder avaliar os produtos cadastrados e ter acesso a futuras atualizações, faça seu login</p>

app/views/layouts/_list_products.html.erb
<% offer_verification = Offer.new %>
<% offers.each do |offer| %>
  <% if offer_verification.product_id != offer.product_id %>
  <% offer_verification = offer %>
    <section class="product">
      <%= link_to list_products_by_name_path(offer.category, offer.subcategory, offer.product.slug), title: 'Clique aqui para ver a lista de preços para este produto' do %>
        <!-- logo company -->
        <div class="text-comp">
          Clique aqui e veja os supermercados que contém este produto
        </div>

        <!-- Image product -->
        <div class="image-product">
          <%= image_tag offer.product.image.thumb %>
        </div>

        <!-- Name product -->
        <h1 class="text-center">
          <%= offer.product.name %>
        </h1>

        <!-- Price -->
        <div class="price text-center">
          <p>A partir de</p>
          <p><%= number_to_currency offer.min_price %></p>
        </div>

        <div class="social text-center">
          Em <b><%= offer.companies %></b> supermercado<%= offer.companies == 1 ? '' : 's' %>
        </div>
      <% end %>
    </section>
  <% end %>
<% end %>

app/views/layouts/_list_products_companies.html.erb
<% offers.each do |offer| %>
  <section class="product">
    <!-- logo company -->
    <div class="logo-comp">
      <div class="text-left">
        <%= image_tag offer.company.logo.thumb, height: 30 %>
      </div>
      <div class="text-right"></div>
    </div>

    <!-- Image product -->
    <div class="image-product text-center">
      <%= image_tag offer.product.image.thumb, height: 120 %>
    </div>

    <!-- Name product -->
    <h1 class="text-center">
      <%= offer.product.name %>
    </h1>

    <!-- Price -->
    <div class="price text-center">
      <p><%= 'de ' << number_to_currency(offer.regular_price).to_s if offer.regular_price.present? %></p>
      <p><%= number_to_currency offer.offer_price %></p>
    </div>

    <div class="social text-center">
      <%= link_to '#' do %>
        <i class="fa fa-facebook-square"></i> Compartilhar
      <% end %>
      <div>Ofertas válidas de <%= offer.start_date %> à  <%= offer.end_date %> de <%= offer.month %><br /> ou enquanto durar os estoques</div>
    </div>
  </section>
<% end %>

app/views/layouts/_list_products_name.html.erb
<% offers.each do |offer| %>
  <section class="product">
    <!-- logo company -->
    <div class="logo-comp">
      <div class="text-left">
        <%= link_to company_path(offer.company.line_of_business.slug, offer.company.slug) do %>
          <%= image_tag offer.company.logo.thumb, height: 30 %>
        <% end %>
      </div>
      <div class="text-right"></div>
    </div>

    <!-- Image product -->
    <div class="image-product text-center">
      <%= image_tag offer.product.image.thumb, height: 120 %>
    </div>

    <!-- Name product -->
    <h1 class="text-center">
      <%= offer.product.name %>
    </h1>

    <!-- Price -->
    <div class="price text-center">
      <p><%= 'de ' << number_to_currency(offer.regular_price).to_s if offer.regular_price.present? %></p>
      <p><%= number_to_currency offer.offer_price %></p>
    </div>

    <div class="social text-center">
      <%= link_to '#' do %>
        <i class="fa fa-facebook-square"></i> Compartilhar
      <% end %>
      <div>Ofertas válidas de <%= offer.start_date %> à  <%= offer.end_date %> de <%= offer.month %><br /> ou enquanto durar os estoques</div>
    </div>
  </section>
<% end %>

app/views/layouts/_nav_categories.html.erb
<% cache 'nav_categories', skip_digest: true do %>
  <nav>
    <div class='nav-close'>
      <i class="fa fa-times"></i>
    </div>
    <ul>
      <div>
        <%= link_to root_path do %>
          <i class="fa fa-angle-right"></i> Início
        <% end %>
      </div>
      <% ProductCategory.all.order('name asc').each do |category| %>
      <% amount_product_category = Offer.list_by_category(category.slug).size %>
        <% if amount_product_category.to_i > 0 %>
        <li>
          <div>
            <%= link_to list_products_by_category_path(category) do %>
              <i class="fa fa-angle-right"></i> <%= category.name %> <span class="amount-product"> (<%= amount_product_category %>)</span>
            <% end %>
          </div>
          <ul>
            <% category.list_subcategories.each do |subcategory|%>
            <% amount_product_subcategory = Offer.list_by_subcategory(subcategory.slug).size %>
              <% if amount_product_subcategory.to_i > 0 %>
              <li>
                <%= link_to subcategory.name, list_products_by_subcategory_path(category, subcategory) %> <span class="amount-product">(<%= amount_product_subcategory %>)</span>
              </li>
              <% end %>
            <% end %>
          </ul>
        </li>
        <% end %>
      <% end %>
    </ul>
  </nav>

  <div class="logo-aside-title">Empresas em destaque</div>
  <hr />
  <% Company.where(status: true, hightlight: true).order('name asc').each do |company| %>
    <div class="logo-aside">
      <%= link_to company_path(company.line_of_business.slug, company.slug) do %>
        <%= image_tag company.logo.sd_150 %>
      <% end %>
    </div>
  <% end %>
  <div class="logo-aside-title">Empresas</div>
  <hr />
  <% Company.where(status: true, hightlight: false).order('name asc').each do |company| %>
    <div class="logo-aside">
      <%= link_to company_path(company.line_of_business.slug, company.slug) do %>
        <%= image_tag company.logo.sd_150, width: 100 %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="pt-br">
<head>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property='og:title' content='Andemenos.com' />
  <meta property='og:description' content='As melhores ofertas bem perto de você' />
  <meta property='og:url' content='http://www.andemenos.com' />
  <meta property="og:image" content="<%= image_url('andemenos.jpg') %>">
  <meta property="og:image:type" content="image/jpeg">

  <link rel="shortcut icon" type="image/x-icon" href="favicon.png" />
  <title>Andemenos.com - As melhores ofertas bem perto de você</title>
  <meta name="description" content="Veja as ofertas de supermercado de nova andradina e região">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/alerts" %>
  <header>
    <div class="cont-logo-menu-top">
      <div class="center">
        <div class="logo">
          <%= link_to root_path do %>
            <h1>Andemenos.com</h1>
            <h2> - As melhores ofertas bem perto de você</h2>
          <% end %>
        </div>
        <div class="cart">
          <span>
            <span><%= link_to 'Quem somos', about_path %></span>
            <span><%= link_to 'Anuncie', ads_path %></span>
            <% if user_signed_in? %>
            <span><%= link_to 'Sair', destroy_user_session_path, :method => :delete %></span>
            <% end %>
          </span>
        </div>
      </div>
    </div>
    <div class="cont-category-search">
      <div class="center">
        <div class="category-title">
          <%= link_to '#' do %>
          <i class="fa fa-bars nav-menu"></i>
          <% end %>
          <span>Principais categorias em</span>
        </div>
        <div class="search">
          <%= form_tag search_path, :method => 'get' do %>
            <%= text_field_tag :search, params[:search], placeholder: 'Busque por: produto, empresa, marca...' %>
            <%= submit_tag "Search", :value => "" %>
          <% end %>
        </div>
      </div>
    </div>
  </header>

  <div class="cont-products">
    <main><%= yield %></main>
  </div>

  <footer>
    <div class="center">
      <div class="info-footer text-left">
        <p>Ofertas sujeitas a alteração sem previo aviso, imagens ilustrativas.</p>
        <p>Todas as ofertas são de responsábilidade do ofertante.</p>
        <p>Caso haja divergência nos valores, a prioridade é o valor do estabelecimento.</p>
      </div>
      <div class="text-right logo-footer">
        Andemenos.com
      </div>
    </div>
  </footer>
  <div class="bg-overlay"></div>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-67232921-1', 'auto');
    ga('send', 'pageview');
  </script>
</body>
</html>